name: Java CI with Maven

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'pom.xml'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'pom.xml'
    branches: [ "main" ]

jobs:
  cmpile-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Compile with Maven
      run: mvn -B compile --file pom.xml

    - name: Test wit Maven
      run: mvn -B test --file pom.xml
